SET DEFINE OFF

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 204573044, 1, to_date('1/May/21', 'DD-MON-RR'), to_date('24-May-21', 'DD-MON-RR'), 2100);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 313548970, 2, to_date('1/May/21', 'DD-MON-RR'), to_date('25-May-21', 'DD-MON-RR'), 1800);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 321164578, 3, to_date('1/May/21', 'DD-MON-RR'), to_date('3-Jun-21', 'DD-MON-RR'), 2200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 203224684, 4, to_date('1/May/21', 'DD-MON-RR'), to_date('27-May-21', 'DD-MON-RR'), 2200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 202546791, 5, to_date('1/May/21', 'DD-MON-RR'), to_date('5-Jun-21', 'DD-MON-RR'), 2300);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 204579231, 6, to_date('1/May/21', 'DD-MON-RR'), to_date('24-May-21', 'DD-MON-RR'), 2100);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 214597456, 7, to_date('1/May/21', 'DD-MON-RR'), to_date('30-May-21', 'DD-MON-RR'), 2500);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 226547891, 8, to_date('1/May/21', 'DD-MON-RR'), to_date('5-Jun-21', 'DD-MON-RR'), 2700);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 235445789, 9, to_date('1/May/21', 'DD-MON-RR'), to_date('1-Jun-21', 'DD-MON-RR'), 2700);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 345561842, 10, to_date('1/May/21', 'DD-MON-RR'), to_date('2-Jun-21', 'DD-MON-RR'), 2600);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 215433664, 11, to_date('1/May/21', 'DD-MON-RR'), to_date('3-Jun-21', 'DD-MON-RR'), 3000);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 369842154, 12, to_date('1/May/21', 'DD-MON-RR'), to_date('4-Jun-21', 'DD-MON-RR'), 3000);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 313654789, 3, to_date('1/Jun/21', 'DD-MON-RR'), to_date('5-Jun-21', 'DD-MON-RR'), 2100);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 201269457, 3, to_date('1/Jun/21', 'DD-MON-RR'), to_date('6-Jun-21', 'DD-MON-RR'), 2100);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 205668941, 1, to_date('1/May/21', 'DD-MON-RR'), to_date('7-Jun-21', 'DD-MON-RR'), 2000);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 206987423, 2, to_date('1/May/21', 'DD-MON-RR'), to_date('8-Jun-21', 'DD-MON-RR'), 1900);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 305496671, 6, to_date('1/Jun/21', 'DD-MON-RR'), to_date('9-Jun-21', 'DD-MON-RR'), 2200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 300665482, 4, to_date('1/May/21', 'DD-MON-RR'), to_date('10-Jun-21', 'DD-MON-RR'), 2200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 311654789, 4, to_date('1/May/21', 'DD-MON-RR'), to_date('11-Jun-21', 'DD-MON-RR'), 2400);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 202235466, 5, to_date('1/May/21', 'DD-MON-RR'), to_date('12-Jun-21', 'DD-MON-RR'), 2300);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 207998453, 5, to_date('1/Jun/21', 'DD-MON-RR'), to_date('1-Aug-21', 'DD-MON-RR'), 2300);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 308664597, 8, to_date('1/Jun/21', 'DD-MON-RR'), to_date('1-Aug-21', 'DD-MON-RR'), 5400);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 330144569, 8, to_date('1/Jun/21', 'DD-MON-RR'), to_date('1-Aug-21', 'DD-MON-RR'), 5400);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 221165485, 11, to_date('1/Jun/21', 'DD-MON-RR'), to_date('2-Aug-21', 'DD-MON-RR'), 6200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 204145349, 11, to_date('1/Jun/21', 'DD-MON-RR'), to_date('2-Aug-21', 'DD-MON-RR'), 6400);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 204654478, 9, to_date('1/Jun/21', 'DD-MON-RR'), to_date('1-Aug-21', 'DD-MON-RR'), 2800);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 206452137, 11, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 3400);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 320557498, 11, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 3000);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 350569874, 9, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 2600);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 313215747, 12, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 3200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 312679137, 12, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 3200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, TENANT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (APARTMENT_PAYMENTS_PAYMENT_ID.NEXTVAL, 204875432, 12, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 3200);
