SET DEFINE OFF

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (1, 'horticulture', 204573044, 'Work on the yard');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (2, 'plumbing', 313548970, 'Clogging in the bath');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (3, 'renovation', 321164578, 'Painting the apartment');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (4, 'renovation', 203224684, 'Painting the apartment');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (5, 'horticulture', 202546791, 'Work on the yard');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (6, 'plumbing', 204579231, 'Clogging in the bath');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (7, 'security', 214597456, 'security system maintenance');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (8, 'renovation', 226547891, 'Shower renewal');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (9, 'renovation', 235445789, 'yearly paint job');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (10, 'plumbing', 345561842, 'clogged toilet');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (11, 'horticulture', 215433664, 'Work on the yard');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (12, 'plumbing', 369842154, 'clogged toilet');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (13, 'cleaning', 313654789, 'Cleaning the building');

INSERT INTO JOBS (JOB_ID, JOB_TYPE, TENANT_ID, DESCRIPTION) 
VALUES (14, 'plumbing', 226547891, 'Building''s pipes cleanup');

