SET DEFINE OFF

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (1, 1, to_date('1/May/21', 'DD-MON-RR'), to_date('24-May-21', 'DD-MON-RR'), 2100);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (2, 2, to_date('1/May/21', 'DD-MON-RR'), to_date('25-May-21', 'DD-MON-RR'), 1800);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (3, 3, to_date('1/May/21', 'DD-MON-RR'), to_date('3-Jun-21', 'DD-MON-RR'), 2200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (4, 4, to_date('1/May/21', 'DD-MON-RR'), to_date('27-May-21', 'DD-MON-RR'), 2200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (5, 5, to_date('1/May/21', 'DD-MON-RR'), to_date('5-Jun-21', 'DD-MON-RR'), 2300);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (6, 6, to_date('1/May/21', 'DD-MON-RR'), to_date('24-May-21', 'DD-MON-RR'), 2100);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (7, 7, to_date('1/May/21', 'DD-MON-RR'), to_date('30-May-21', 'DD-MON-RR'), 2500);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (8, 8, to_date('1/May/21', 'DD-MON-RR'), to_date('5-Jun-21', 'DD-MON-RR'), 2700);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (9, 9, to_date('1/May/21', 'DD-MON-RR'), to_date('1-Jun-21', 'DD-MON-RR'), 2700);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (10, 10, to_date('1/May/21', 'DD-MON-RR'), to_date('2-Jun-21', 'DD-MON-RR'), 2600);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (11, 11, to_date('1/May/21', 'DD-MON-RR'), to_date('3-Jun-21', 'DD-MON-RR'), 3000);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (12, 12, to_date('1/May/21', 'DD-MON-RR'), to_date('4-Jun-21', 'DD-MON-RR'), 3000);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (13, 3, to_date('1/Jun/21', 'DD-MON-RR'), to_date('5-Jun-21', 'DD-MON-RR'), 2100);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (14, 3, to_date('1/Jun/21', 'DD-MON-RR'), to_date('6-Jun-21', 'DD-MON-RR'), 2100);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (15, 1, to_date('1/May/21', 'DD-MON-RR'), to_date('7-Jun-21', 'DD-MON-RR'), 2000);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (16, 2, to_date('1/May/21', 'DD-MON-RR'), to_date('8-Jun-21', 'DD-MON-RR'), 1900);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (17, 6, to_date('1/Jun/21', 'DD-MON-RR'), to_date('9-Jun-21', 'DD-MON-RR'), 2200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (18, 4, to_date('1/May/21', 'DD-MON-RR'), to_date('10-Jun-21', 'DD-MON-RR'), 2200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (19, 4, to_date('1/May/21', 'DD-MON-RR'), to_date('11-Jun-21', 'DD-MON-RR'), 2400);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (20, 5, to_date('1/May/21', 'DD-MON-RR'), to_date('12-Jun-21', 'DD-MON-RR'), 2300);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (21, 5, to_date('1/Jun/21', 'DD-MON-RR'), to_date('1-Aug-21', 'DD-MON-RR'), 2300);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (22, 8, to_date('1/Jun/21', 'DD-MON-RR'), to_date('1-Aug-21', 'DD-MON-RR'), 5400);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (23, 8, to_date('1/Jun/21', 'DD-MON-RR'), to_date('1-Aug-21', 'DD-MON-RR'), 5400);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (24, 11, to_date('1/Jun/21', 'DD-MON-RR'), to_date('2-Aug-21', 'DD-MON-RR'), 6200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (25, 11, to_date('1/Jun/21', 'DD-MON-RR'), to_date('2-Aug-21', 'DD-MON-RR'), 6400);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (26, 9, to_date('1/Jun/21', 'DD-MON-RR'), to_date('1-Aug-21', 'DD-MON-RR'), 2800);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (27, 11, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 3400);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (28, 11, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 3000);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (29, 9, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 2600);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (30, 12, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 3200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (31, 12, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 3200);

INSERT INTO APARTMENT_PAYMENTS (PAYMENT_ID, APARTMENT_ID, MONTH, PAYMENT_DATE, AMOUNT) 
VALUES (32, 12, to_date('1/Jul/21', 'DD-MON-RR'), to_date('1-Sep-21', 'DD-MON-RR'), 3200);

