SET DEFINE OFF

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (1, 2, 50);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (2, 2, 50);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (3, 3, 80);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (4, 4, 100);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (5, 3, 80);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (6, 2, 50);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (7, 3, 80);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (8, 3, 80);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (9, 3, 80);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (10, 4, 100);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (11, 5, 120);

INSERT INTO APARTMENT (APARTMENT_ID, TENANTS_NUMBER, "size") 
VALUES (12, 4, 100);

