SET DEFINE OFF

INSERT INTO JOBS_PLANS (PLAN_ID, JOB_ID) 
VALUES (1, 13);

INSERT INTO JOBS_PLANS (PLAN_ID, JOB_ID) 
VALUES (2, 8);

INSERT INTO JOBS_PLANS (PLAN_ID, JOB_ID) 
VALUES (3, 14);

INSERT INTO JOBS_PLANS (PLAN_ID, JOB_ID) 
VALUES (4, 9);

INSERT INTO JOBS_PLANS (PLAN_ID, JOB_ID) 
VALUES (5, 7);

INSERT INTO JOBS_PLANS (PLAN_ID, JOB_ID) 
VALUES (6, 5);

INSERT INTO JOBS_PLANS (PLAN_ID, JOB_ID) 
VALUES (7, 3);

INSERT INTO JOBS_PLANS (PLAN_ID, JOB_ID) 
VALUES (8, 1);

INSERT INTO JOBS_PLANS (PLAN_ID, JOB_ID) 
VALUES (9, 12);

INSERT INTO JOBS_PLANS (PLAN_ID, JOB_ID) 
VALUES (10, 4);

