SET DEFINE OFF

INSERT INTO CONTRACTORS (CONTRACTOR_ID, CONTRACTOR_NAME, ADDRESS) 
VALUES (245432256, 'Avi Mizrachi', 'Serlin Yosef 40 Holon');

INSERT INTO CONTRACTORS (CONTRACTOR_ID, CONTRACTOR_NAME, ADDRESS) 
VALUES (987678765, 'Ben Zacahi', 'Sokolov 30 Tel Aviv');

INSERT INTO CONTRACTORS (CONTRACTOR_ID, CONTRACTOR_NAME, ADDRESS) 
VALUES (654235247, 'Dan Kissilevitz', 'Rotman 22 Rosh Aayn');

INSERT INTO CONTRACTORS (CONTRACTOR_ID, CONTRACTOR_NAME, ADDRESS) 
VALUES (213233567, 'Kiril Bortman', 'Batyamon 2 Bat Yam');

INSERT INTO CONTRACTORS (CONTRACTOR_ID, CONTRACTOR_NAME, ADDRESS) 
VALUES (234321234, 'Zohar Zaborski', 'Azocher Zichron Yaakov ');

INSERT INTO CONTRACTORS (CONTRACTOR_ID, CONTRACTOR_NAME, ADDRESS) 
VALUES (345543213, 'Netanel Mizrahi', 'Galia 1 Moshav Galia');

INSERT INTO CONTRACTORS (CONTRACTOR_ID, CONTRACTOR_NAME, ADDRESS) 
VALUES (313222787, 'Max Levi', 'Near Beach Natania');

INSERT INTO CONTRACTORS (CONTRACTOR_ID, CONTRACTOR_NAME, ADDRESS) 
VALUES (123321277, 'Tal Nitzan', 'Glil Yam Herzelia');

INSERT INTO CONTRACTORS (CONTRACTOR_ID, CONTRACTOR_NAME, ADDRESS) 
VALUES (432321268, 'Omer Lev Ron', 'Nitzana Rishon lezion');

INSERT INTO CONTRACTORS (CONTRACTOR_ID, CONTRACTOR_NAME, ADDRESS) 
VALUES (313255665, 'Sam Medina', 'Ahon 30 Holon');

