SET DEFINE OFF

INSERT INTO CONTRACTORS_PAYMENTS (PAYMENT_ID, JOB_ID, "date", PRICE, PAYMENT_DESCRIPTION) 
VALUES (1, 4, to_date('24-May-21', 'DD-MON-RR'), 500, '1 payment of 500');

INSERT INTO CONTRACTORS_PAYMENTS (PAYMENT_ID, JOB_ID, "date", PRICE, PAYMENT_DESCRIPTION) 
VALUES (2, 5, to_date('25-May-21', 'DD-MON-RR'), 6000, '6 payment of 1000');

INSERT INTO CONTRACTORS_PAYMENTS (PAYMENT_ID, JOB_ID, "date", PRICE, PAYMENT_DESCRIPTION) 
VALUES (3, 10, to_date('30-Oct-21', 'DD-MON-RR'), 1000, '2 payment of 500');

INSERT INTO CONTRACTORS_PAYMENTS (PAYMENT_ID, JOB_ID, "date", PRICE, PAYMENT_DESCRIPTION) 
VALUES (4, 11, to_date('1-Nov-21', 'DD-MON-RR'), 900, '3 payment of 300');

INSERT INTO CONTRACTORS_PAYMENTS (PAYMENT_ID, JOB_ID, "date", PRICE, PAYMENT_DESCRIPTION) 
VALUES (5, 12, to_date('2-Nov-21', 'DD-MON-RR'), 1050, '1 payment of 1050');

INSERT INTO CONTRACTORS_PAYMENTS (PAYMENT_ID, JOB_ID, "date", PRICE, PAYMENT_DESCRIPTION) 
VALUES (6, 13, to_date('11-Nov-21', 'DD-MON-RR'), 3500, '7 payment of 500');

INSERT INTO CONTRACTORS_PAYMENTS (PAYMENT_ID, JOB_ID, "date", PRICE, PAYMENT_DESCRIPTION) 
VALUES (7, 6, to_date('30-Jun-21', 'DD-MON-RR'), 2000, '4 payment of 500');

INSERT INTO CONTRACTORS_PAYMENTS (PAYMENT_ID, JOB_ID, "date", PRICE, PAYMENT_DESCRIPTION) 
VALUES (8, 7, to_date('23-Jul-21', 'DD-MON-RR'), 2000, '2 payment of 1000');

INSERT INTO CONTRACTORS_PAYMENTS (PAYMENT_ID, JOB_ID, "date", PRICE, PAYMENT_DESCRIPTION) 
VALUES (9, 8, to_date('1-Jun-21', 'DD-MON-RR'), 3250, '1 payment of 3250');

INSERT INTO CONTRACTORS_PAYMENTS (PAYMENT_ID, JOB_ID, "date", PRICE, PAYMENT_DESCRIPTION) 
VALUES (10, 9, to_date('10-Jun-21', 'DD-MON-RR'), 1000, '10 payment of 100');

